# Generated by Django 5.2.8 on 2025-11-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contenido', models.TextField(help_text='Texto que saldrá en el PDF')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
